/* Generated by npm run build. */
window.LARA_IZA_CONFIG = {
  SUPABASE_URL: "https://vlgkckssqoceimlklmqj.supabase.co",
  SUPABASE_ANON_KEY: "sb_publishable_rzMRJd-cROPEqcdnAf6wEQ_1nKqfMz6",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_rzMRJd-cROPEqcdnAf6wEQ_1nKqfMz6",
  APP_NAME: 'Lara Iza',
  SUPPORT_EMAIL: "suporte@laraiza.com"
};
