import { existsSync, readFileSync, writeFileSync } from 'node:fs';

function loadDotEnv(path = '.env') {
  if (!existsSync(path)) return {};
  const out = {};
  for (const raw of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const i = line.indexOf('=');
    if (i < 0) continue;
    const key = line.slice(0, i).trim();
    let value = line.slice(i + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    out[key] = value;
  }
  return out;
}

const env = { ...loadDotEnv(), ...process.env };
const url = env.SUPABASE_URL || 'https://vlgkckssqoceimlklmqj.supabase.co';
const key = env.SUPABASE_PUBLISHABLE_KEY || env.SUPABASE_ANON_KEY || 'sb_publishable_rzMRJd-cROPEqcdnAf6wEQ_1nKqfMz6';
const support = env.SUPPORT_EMAIL || 'suporte@laraiza.com';

if (!url || !key) {
  const productionBuild = env.NETLIFY === 'true' || env.CI === 'true' || env.REQUIRE_SUPABASE === 'true';
  if (productionBuild) {
    console.error('ERRO: SUPABASE_URL e SUPABASE_PUBLISHABLE_KEY precisam estar configuradas.');
    process.exit(1);
  }
}

const safe = (value) => JSON.stringify(value);
const output = `/* Generated by npm run build. */\nwindow.LARA_IZA_CONFIG = {\n  SUPABASE_URL: ${safe(url)},\n  SUPABASE_ANON_KEY: ${safe(key)},\n  SUPABASE_PUBLISHABLE_KEY: ${safe(key)},\n  APP_NAME: 'Lara Iza',\n  SUPPORT_EMAIL: ${safe(support)}\n};\n`;
writeFileSync('supabase-config.js', output, 'utf8');
console.log('Supabase runtime configuration generated successfully.');
